/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence;


import cn.luixtech.passport.server.persistence.tables.RolePermission;
import cn.luixtech.passport.server.persistence.tables.User;
import cn.luixtech.passport.server.persistence.tables.UserLogin;
import cn.luixtech.passport.server.persistence.tables.UserNotification;
import cn.luixtech.passport.server.persistence.tables.UserRole;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_ROLE_PERMISSION_PERMISSION_ID = Internal.createIndex(DSL.name("idx_role_permission_permission_id"), RolePermission.ROLE_PERMISSION, new OrderField[] { RolePermission.ROLE_PERMISSION.PERMISSION_ID }, false);
    public static final Index IDX_ROLE_PERMISSION_ROLE_ID = Internal.createIndex(DSL.name("idx_role_permission_role_id"), RolePermission.ROLE_PERMISSION, new OrderField[] { RolePermission.ROLE_PERMISSION.ROLE_ID }, false);
    public static final Index IDX_USER_DATE_TIME_FORMAT_ID = Internal.createIndex(DSL.name("idx_user_date_time_format_id"), User.USER, new OrderField[] { User.USER.DATE_TIME_FORMAT_ID }, false);
    public static final Index IDX_USER_LOGIN_USERNAME = Internal.createIndex(DSL.name("idx_user_login_username"), UserLogin.USER_LOGIN, new OrderField[] { UserLogin.USER_LOGIN.USERNAME }, false);
    public static final Index IDX_USER_NOTIFICATION_NOTIFICATION = Internal.createIndex(DSL.name("idx_user_notification_notification"), UserNotification.USER_NOTIFICATION, new OrderField[] { UserNotification.USER_NOTIFICATION.NOTIFICATION_ID }, false);
    public static final Index IDX_USER_NOTIFICATION_USER_STATUS = Internal.createIndex(DSL.name("idx_user_notification_user_status"), UserNotification.USER_NOTIFICATION, new OrderField[] { UserNotification.USER_NOTIFICATION.RECEIVER_ID, UserNotification.USER_NOTIFICATION.STATUS }, false);
    public static final Index IDX_USER_ROLE_ROLE_ID = Internal.createIndex(DSL.name("idx_user_role_role_id"), UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE_ID }, false);
    public static final Index IDX_USER_ROLE_USERNAME = Internal.createIndex(DSL.name("idx_user_role_username"), UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USERNAME }, false);
    public static final Index IDX_USER_TIME_ZONE_ID = Internal.createIndex(DSL.name("idx_user_time_zone_id"), User.USER, new OrderField[] { User.USER.TIME_ZONE_ID }, false);
}
