/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence;


import cn.luixtech.passport.server.persistence.tables.DataDict;
import cn.luixtech.passport.server.persistence.tables.Notification;
import cn.luixtech.passport.server.persistence.tables.Oauth2Authorization;
import cn.luixtech.passport.server.persistence.tables.Oauth2AuthorizationConsent;
import cn.luixtech.passport.server.persistence.tables.Oauth2RegisteredClient;
import cn.luixtech.passport.server.persistence.tables.Permission;
import cn.luixtech.passport.server.persistence.tables.Role;
import cn.luixtech.passport.server.persistence.tables.RolePermission;
import cn.luixtech.passport.server.persistence.tables.SpringSession;
import cn.luixtech.passport.server.persistence.tables.SpringSessionAttributes;
import cn.luixtech.passport.server.persistence.tables.SupportedDateTimeFormat;
import cn.luixtech.passport.server.persistence.tables.TableSeqNumber;
import cn.luixtech.passport.server.persistence.tables.Team;
import cn.luixtech.passport.server.persistence.tables.TeamUser;
import cn.luixtech.passport.server.persistence.tables.User;
import cn.luixtech.passport.server.persistence.tables.UserAuthEvent;
import cn.luixtech.passport.server.persistence.tables.UserLogin;
import cn.luixtech.passport.server.persistence.tables.UserNotification;
import cn.luixtech.passport.server.persistence.tables.UserProfilePic;
import cn.luixtech.passport.server.persistence.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.data_dict</code>.
     */
    public final DataDict DATA_DICT = DataDict.DATA_DICT;

    /**
     * The table <code>public.notification</code>.
     */
    public final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>public.oauth2_authorization</code>.
     */
    public final Oauth2Authorization OAUTH2_AUTHORIZATION = Oauth2Authorization.OAUTH2_AUTHORIZATION;

    /**
     * The table <code>public.oauth2_authorization_consent</code>.
     */
    public final Oauth2AuthorizationConsent OAUTH2_AUTHORIZATION_CONSENT = Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT;

    /**
     * The table <code>public.oauth2_registered_client</code>.
     */
    public final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT;

    /**
     * The table <code>public.permission</code>.
     */
    public final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permission</code>.
     */
    public final RolePermission ROLE_PERMISSION = RolePermission.ROLE_PERMISSION;

    /**
     * The table <code>public.spring_session</code>.
     */
    public final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>public.spring_session_attributes</code>.
     */
    public final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;

    /**
     * The table <code>public.supported_date_time_format</code>.
     */
    public final SupportedDateTimeFormat SUPPORTED_DATE_TIME_FORMAT = SupportedDateTimeFormat.SUPPORTED_DATE_TIME_FORMAT;

    /**
     * The table <code>public.table_seq_number</code>.
     */
    public final TableSeqNumber TABLE_SEQ_NUMBER = TableSeqNumber.TABLE_SEQ_NUMBER;

    /**
     * The table <code>public.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_user</code>.
     */
    public final TeamUser TEAM_USER = TeamUser.TEAM_USER;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_auth_event</code>.
     */
    public final UserAuthEvent USER_AUTH_EVENT = UserAuthEvent.USER_AUTH_EVENT;

    /**
     * The table <code>public.user_login</code>.
     */
    public final UserLogin USER_LOGIN = UserLogin.USER_LOGIN;

    /**
     * The table <code>public.user_notification</code>.
     */
    public final UserNotification USER_NOTIFICATION = UserNotification.USER_NOTIFICATION;

    /**
     * The table <code>public.user_profile_pic</code>.
     */
    public final UserProfilePic USER_PROFILE_PIC = UserProfilePic.USER_PROFILE_PIC;

    /**
     * The table <code>public.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DataDict.DATA_DICT,
            Notification.NOTIFICATION,
            Oauth2Authorization.OAUTH2_AUTHORIZATION,
            Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT,
            Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT,
            Permission.PERMISSION,
            Role.ROLE,
            RolePermission.ROLE_PERMISSION,
            SpringSession.SPRING_SESSION,
            SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES,
            SupportedDateTimeFormat.SUPPORTED_DATE_TIME_FORMAT,
            TableSeqNumber.TABLE_SEQ_NUMBER,
            Team.TEAM,
            TeamUser.TEAM_USER,
            User.USER,
            UserAuthEvent.USER_AUTH_EVENT,
            UserLogin.USER_LOGIN,
            UserNotification.USER_NOTIFICATION,
            UserProfilePic.USER_PROFILE_PIC,
            UserRole.USER_ROLE
        );
    }
}
