/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.JobQueue;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobQueueRecord extends UpdatableRecordImpl<JobQueueRecord> implements Record6<String, String, JSONB, String, Instant, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.job_queue.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.job_queue.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.job_queue.job_type</code>.
     */
    public void setJobType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.job_queue.job_type</code>.
     */
    public String getJobType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.job_queue.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.job_queue.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.job_queue.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.job_queue.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.job_queue.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.job_queue.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.job_queue.processed_at</code>.
     */
    public void setProcessedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.job_queue.processed_at</code>.
     */
    public Instant getProcessedAt() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, JSONB, String, Instant, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, JSONB, String, Instant, Instant> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JobQueue.JOB_QUEUE.ID;
    }

    @Override
    public Field<String> field2() {
        return JobQueue.JOB_QUEUE.JOB_TYPE;
    }

    @Override
    public Field<JSONB> field3() {
        return JobQueue.JOB_QUEUE.PAYLOAD;
    }

    @Override
    public Field<String> field4() {
        return JobQueue.JOB_QUEUE.STATUS;
    }

    @Override
    public Field<Instant> field5() {
        return JobQueue.JOB_QUEUE.CREATED_AT;
    }

    @Override
    public Field<Instant> field6() {
        return JobQueue.JOB_QUEUE.PROCESSED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getJobType();
    }

    @Override
    public JSONB component3() {
        return getPayload();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public Instant component5() {
        return getCreatedAt();
    }

    @Override
    public Instant component6() {
        return getProcessedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getJobType();
    }

    @Override
    public JSONB value3() {
        return getPayload();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public Instant value5() {
        return getCreatedAt();
    }

    @Override
    public Instant value6() {
        return getProcessedAt();
    }

    @Override
    public JobQueueRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public JobQueueRecord value2(String value) {
        setJobType(value);
        return this;
    }

    @Override
    public JobQueueRecord value3(JSONB value) {
        setPayload(value);
        return this;
    }

    @Override
    public JobQueueRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public JobQueueRecord value5(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public JobQueueRecord value6(Instant value) {
        setProcessedAt(value);
        return this;
    }

    @Override
    public JobQueueRecord values(String value1, String value2, JSONB value3, String value4, Instant value5, Instant value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobQueueRecord
     */
    public JobQueueRecord() {
        super(JobQueue.JOB_QUEUE);
    }

    /**
     * Create a detached, initialised JobQueueRecord
     */
    public JobQueueRecord(String id, String jobType, JSONB payload, String status, Instant createdAt, Instant processedAt) {
        super(JobQueue.JOB_QUEUE);

        setId(id);
        setJobType(jobType);
        setPayload(payload);
        setStatus(status);
        setCreatedAt(createdAt);
        setProcessedAt(processedAt);
        resetChangedOnNotNull();
    }
}
