/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.JobQueue;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobQueueRecord extends UpdatableRecordImpl<JobQueueRecord> implements Record8<String, String, JSONB, Integer, String, String, Instant, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.job_queue.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.job_queue.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.job_queue.channel</code>.
     */
    public void setChannel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.job_queue.channel</code>.
     */
    public String getChannel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.job_queue.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.job_queue.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.job_queue.priority</code>.
     */
    public void setPriority(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.job_queue.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.job_queue.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.job_queue.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.job_queue.error</code>.
     */
    public void setError(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.job_queue.error</code>.
     */
    public String getError() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.job_queue.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.job_queue.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.job_queue.processed_at</code>.
     */
    public void setProcessedAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.job_queue.processed_at</code>.
     */
    public Instant getProcessedAt() {
        return (Instant) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, JSONB, Integer, String, String, Instant, Instant> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, JSONB, Integer, String, String, Instant, Instant> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JobQueue.JOB_QUEUE.ID;
    }

    @Override
    public Field<String> field2() {
        return JobQueue.JOB_QUEUE.CHANNEL;
    }

    @Override
    public Field<JSONB> field3() {
        return JobQueue.JOB_QUEUE.PAYLOAD;
    }

    @Override
    public Field<Integer> field4() {
        return JobQueue.JOB_QUEUE.PRIORITY;
    }

    @Override
    public Field<String> field5() {
        return JobQueue.JOB_QUEUE.STATUS;
    }

    @Override
    public Field<String> field6() {
        return JobQueue.JOB_QUEUE.ERROR;
    }

    @Override
    public Field<Instant> field7() {
        return JobQueue.JOB_QUEUE.CREATED_AT;
    }

    @Override
    public Field<Instant> field8() {
        return JobQueue.JOB_QUEUE.PROCESSED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getChannel();
    }

    @Override
    public JSONB component3() {
        return getPayload();
    }

    @Override
    public Integer component4() {
        return getPriority();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getError();
    }

    @Override
    public Instant component7() {
        return getCreatedAt();
    }

    @Override
    public Instant component8() {
        return getProcessedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getChannel();
    }

    @Override
    public JSONB value3() {
        return getPayload();
    }

    @Override
    public Integer value4() {
        return getPriority();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getError();
    }

    @Override
    public Instant value7() {
        return getCreatedAt();
    }

    @Override
    public Instant value8() {
        return getProcessedAt();
    }

    @Override
    public JobQueueRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public JobQueueRecord value2(String value) {
        setChannel(value);
        return this;
    }

    @Override
    public JobQueueRecord value3(JSONB value) {
        setPayload(value);
        return this;
    }

    @Override
    public JobQueueRecord value4(Integer value) {
        setPriority(value);
        return this;
    }

    @Override
    public JobQueueRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public JobQueueRecord value6(String value) {
        setError(value);
        return this;
    }

    @Override
    public JobQueueRecord value7(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public JobQueueRecord value8(Instant value) {
        setProcessedAt(value);
        return this;
    }

    @Override
    public JobQueueRecord values(String value1, String value2, JSONB value3, Integer value4, String value5, String value6, Instant value7, Instant value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobQueueRecord
     */
    public JobQueueRecord() {
        super(JobQueue.JOB_QUEUE);
    }

    /**
     * Create a detached, initialised JobQueueRecord
     */
    public JobQueueRecord(String id, String channel, JSONB payload, Integer priority, String status, String error, Instant createdAt, Instant processedAt) {
        super(JobQueue.JOB_QUEUE);

        setId(id);
        setChannel(channel);
        setPayload(payload);
        setPriority(priority);
        setStatus(status);
        setError(error);
        setCreatedAt(createdAt);
        setProcessedAt(processedAt);
        resetChangedOnNotNull();
    }
}
