/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.Notification;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record7<String, String, String, String, String, Instant, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notification.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.notification.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.notification.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notification.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.notification.sender_id</code>.
     */
    public void setSenderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification.sender_id</code>.
     */
    public String getSenderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.notification.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notification.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.notification.modified_at</code>.
     */
    public void setModifiedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.notification.modified_at</code>.
     */
    public Instant getModifiedAt() {
        return (Instant) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, Instant, Instant> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, Instant, Instant> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Notification.NOTIFICATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Notification.NOTIFICATION.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Notification.NOTIFICATION.CONTENT;
    }

    @Override
    public Field<String> field4() {
        return Notification.NOTIFICATION.TYPE;
    }

    @Override
    public Field<String> field5() {
        return Notification.NOTIFICATION.SENDER_ID;
    }

    @Override
    public Field<Instant> field6() {
        return Notification.NOTIFICATION.CREATED_AT;
    }

    @Override
    public Field<Instant> field7() {
        return Notification.NOTIFICATION.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getSenderId();
    }

    @Override
    public Instant component6() {
        return getCreatedAt();
    }

    @Override
    public Instant component7() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getSenderId();
    }

    @Override
    public Instant value6() {
        return getCreatedAt();
    }

    @Override
    public Instant value7() {
        return getModifiedAt();
    }

    @Override
    public NotificationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public NotificationRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public NotificationRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public NotificationRecord value5(String value) {
        setSenderId(value);
        return this;
    }

    @Override
    public NotificationRecord value6(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationRecord value7(Instant value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public NotificationRecord values(String value1, String value2, String value3, String value4, String value5, Instant value6, Instant value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(String id, String title, String content, String type, String senderId, Instant createdAt, Instant modifiedAt) {
        super(Notification.NOTIFICATION);

        setId(id);
        setTitle(title);
        setContent(content);
        setType(type);
        setSenderId(senderId);
        setCreatedAt(createdAt);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
