/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.Org;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrgRecord extends UpdatableRecordImpl<OrgRecord> implements Record4<String, String, Boolean, byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.org.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.org.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.org.remark</code>.
     */
    public void setRemark(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.org.remark</code>.
     */
    public String getRemark() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.org.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.org.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.org.photo</code>.
     */
    public void setPhoto(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.org.photo</code>.
     */
    public byte[] getPhoto() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Boolean, byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, Boolean, byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Org.ORG.ID;
    }

    @Override
    public Field<String> field2() {
        return Org.ORG.REMARK;
    }

    @Override
    public Field<Boolean> field3() {
        return Org.ORG.ENABLED;
    }

    @Override
    public Field<byte[]> field4() {
        return Org.ORG.PHOTO;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRemark();
    }

    @Override
    public Boolean component3() {
        return getEnabled();
    }

    @Override
    public byte[] component4() {
        return getPhoto();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRemark();
    }

    @Override
    public Boolean value3() {
        return getEnabled();
    }

    @Override
    public byte[] value4() {
        return getPhoto();
    }

    @Override
    public OrgRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public OrgRecord value2(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public OrgRecord value3(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public OrgRecord value4(byte[] value) {
        setPhoto(value);
        return this;
    }

    @Override
    public OrgRecord values(String value1, String value2, Boolean value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgRecord
     */
    public OrgRecord() {
        super(Org.ORG);
    }

    /**
     * Create a detached, initialised OrgRecord
     */
    public OrgRecord(String id, String remark, Boolean enabled, byte[] photo) {
        super(Org.ORG);

        setId(id);
        setRemark(remark);
        setEnabled(enabled);
        setPhoto(photo);
        resetChangedOnNotNull();
    }
}
