/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.Permission;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermissionRecord extends UpdatableRecordImpl<PermissionRecord> implements Record6<String, String, String, String, Instant, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.permission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.permission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.permission.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.permission.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.permission.resource_type</code>.
     */
    public void setResourceType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.permission.resource_type</code>.
     */
    public String getResourceType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.permission.action</code>.
     */
    public void setAction(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.permission.action</code>.
     */
    public String getAction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.permission.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.permission.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.permission.modified_at</code>.
     */
    public void setModifiedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.permission.modified_at</code>.
     */
    public Instant getModifiedAt() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, Instant, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, Instant, Instant> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Permission.PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return Permission.PERMISSION.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return Permission.PERMISSION.RESOURCE_TYPE;
    }

    @Override
    public Field<String> field4() {
        return Permission.PERMISSION.ACTION;
    }

    @Override
    public Field<Instant> field5() {
        return Permission.PERMISSION.CREATED_AT;
    }

    @Override
    public Field<Instant> field6() {
        return Permission.PERMISSION.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getResourceType();
    }

    @Override
    public String component4() {
        return getAction();
    }

    @Override
    public Instant component5() {
        return getCreatedAt();
    }

    @Override
    public Instant component6() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getResourceType();
    }

    @Override
    public String value4() {
        return getAction();
    }

    @Override
    public Instant value5() {
        return getCreatedAt();
    }

    @Override
    public Instant value6() {
        return getModifiedAt();
    }

    @Override
    public PermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PermissionRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PermissionRecord value3(String value) {
        setResourceType(value);
        return this;
    }

    @Override
    public PermissionRecord value4(String value) {
        setAction(value);
        return this;
    }

    @Override
    public PermissionRecord value5(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PermissionRecord value6(Instant value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public PermissionRecord values(String value1, String value2, String value3, String value4, Instant value5, Instant value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionRecord
     */
    public PermissionRecord() {
        super(Permission.PERMISSION);
    }

    /**
     * Create a detached, initialised PermissionRecord
     */
    public PermissionRecord(String id, String description, String resourceType, String action, Instant createdAt, Instant modifiedAt) {
        super(Permission.PERMISSION);

        setId(id);
        setDescription(description);
        setResourceType(resourceType);
        setAction(action);
        setCreatedAt(createdAt);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
