/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.Role;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record6<String, String, Instant, String, Instant, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.role.remark</code>.
     */
    public void setRemark(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role.remark</code>.
     */
    public String getRemark() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.role.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(2);
    }

    /**
     * Setter for <code>public.role.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.role.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.role.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.role.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.role.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.role.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, Instant, String, Instant, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, Instant, String, Instant, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Role.ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return Role.ROLE.REMARK;
    }

    @Override
    public Field<Instant> field3() {
        return Role.ROLE.CREATED_AT;
    }

    @Override
    public Field<String> field4() {
        return Role.ROLE.CREATED_BY;
    }

    @Override
    public Field<Instant> field5() {
        return Role.ROLE.UPDATED_AT;
    }

    @Override
    public Field<String> field6() {
        return Role.ROLE.UPDATED_BY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRemark();
    }

    @Override
    public Instant component3() {
        return getCreatedAt();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public Instant component5() {
        return getUpdatedAt();
    }

    @Override
    public String component6() {
        return getUpdatedBy();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRemark();
    }

    @Override
    public Instant value3() {
        return getCreatedAt();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public Instant value5() {
        return getUpdatedAt();
    }

    @Override
    public String value6() {
        return getUpdatedBy();
    }

    @Override
    public RoleRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public RoleRecord value2(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public RoleRecord value3(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public RoleRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public RoleRecord value5(Instant value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public RoleRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public RoleRecord values(String value1, String value2, Instant value3, String value4, Instant value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(String id, String remark, Instant createdAt, String createdBy, Instant updatedAt, String updatedBy) {
        super(Role.ROLE);

        setId(id);
        setRemark(remark);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }
}
