/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.RolePermission;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RolePermissionRecord extends UpdatableRecordImpl<RolePermissionRecord> implements Record7<String, String, String, Instant, String, Instant, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role_permission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role_permission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.role_permission.role_id</code>.
     */
    public void setRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role_permission.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role_permission.permission_id</code>.
     */
    public void setPermissionId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.role_permission.permission_id</code>.
     */
    public String getPermissionId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.role_permission.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.role_permission.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(3);
    }

    /**
     * Setter for <code>public.role_permission.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.role_permission.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.role_permission.modified_at</code>.
     */
    public void setModifiedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.role_permission.modified_at</code>.
     */
    public Instant getModifiedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.role_permission.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.role_permission.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, Instant, String, Instant, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, Instant, String, Instant, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RolePermission.ROLE_PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return RolePermission.ROLE_PERMISSION.ROLE_ID;
    }

    @Override
    public Field<String> field3() {
        return RolePermission.ROLE_PERMISSION.PERMISSION_ID;
    }

    @Override
    public Field<Instant> field4() {
        return RolePermission.ROLE_PERMISSION.CREATED_AT;
    }

    @Override
    public Field<String> field5() {
        return RolePermission.ROLE_PERMISSION.CREATED_BY;
    }

    @Override
    public Field<Instant> field6() {
        return RolePermission.ROLE_PERMISSION.MODIFIED_AT;
    }

    @Override
    public Field<String> field7() {
        return RolePermission.ROLE_PERMISSION.MODIFIED_BY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRoleId();
    }

    @Override
    public String component3() {
        return getPermissionId();
    }

    @Override
    public Instant component4() {
        return getCreatedAt();
    }

    @Override
    public String component5() {
        return getCreatedBy();
    }

    @Override
    public Instant component6() {
        return getModifiedAt();
    }

    @Override
    public String component7() {
        return getModifiedBy();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRoleId();
    }

    @Override
    public String value3() {
        return getPermissionId();
    }

    @Override
    public Instant value4() {
        return getCreatedAt();
    }

    @Override
    public String value5() {
        return getCreatedBy();
    }

    @Override
    public Instant value6() {
        return getModifiedAt();
    }

    @Override
    public String value7() {
        return getModifiedBy();
    }

    @Override
    public RolePermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value2(String value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value3(String value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value4(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public RolePermissionRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public RolePermissionRecord value6(Instant value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public RolePermissionRecord value7(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public RolePermissionRecord values(String value1, String value2, String value3, Instant value4, String value5, Instant value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionRecord
     */
    public RolePermissionRecord() {
        super(RolePermission.ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(String id, String roleId, String permissionId, Instant createdAt, String createdBy, Instant modifiedAt, String modifiedBy) {
        super(RolePermission.ROLE_PERMISSION);

        setId(id);
        setRoleId(roleId);
        setPermissionId(permissionId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        resetChangedOnNotNull();
    }
}
