/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.RolePermission;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RolePermissionRecord extends UpdatableRecordImpl<RolePermissionRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role_permission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role_permission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.role_permission.role_id</code>.
     */
    public void setRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role_permission.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role_permission.permission_id</code>.
     */
    public void setPermissionId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.role_permission.permission_id</code>.
     */
    public String getPermissionId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RolePermission.ROLE_PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return RolePermission.ROLE_PERMISSION.ROLE_ID;
    }

    @Override
    public Field<String> field3() {
        return RolePermission.ROLE_PERMISSION.PERMISSION_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRoleId();
    }

    @Override
    public String component3() {
        return getPermissionId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRoleId();
    }

    @Override
    public String value3() {
        return getPermissionId();
    }

    @Override
    public RolePermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value2(String value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolePermissionRecord value3(String value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public RolePermissionRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionRecord
     */
    public RolePermissionRecord() {
        super(RolePermission.ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(String id, String roleId, String permissionId) {
        super(RolePermission.ROLE_PERMISSION);

        setId(id);
        setRoleId(roleId);
        setPermissionId(permissionId);
        resetChangedOnNotNull();
    }
}
