/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.ScheduleExecutionLog;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScheduleExecutionLogRecord extends UpdatableRecordImpl<ScheduleExecutionLogRecord> implements Record12<String, String, Instant, Instant, Long, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.schedule_execution_log.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.schedule_execution_log.task_name</code>.
     */
    public void setTaskName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.task_name</code>.
     */
    public String getTaskName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.schedule_execution_log.start_time</code>.
     */
    public void setStartTime(Instant value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.start_time</code>.
     */
    public Instant getStartTime() {
        return (Instant) get(2);
    }

    /**
     * Setter for <code>public.schedule_execution_log.end_time</code>.
     */
    public void setEndTime(Instant value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.end_time</code>.
     */
    public Instant getEndTime() {
        return (Instant) get(3);
    }

    /**
     * Setter for <code>public.schedule_execution_log.duration_ms</code>.
     */
    public void setDurationMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.duration_ms</code>.
     */
    public Long getDurationMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.schedule_execution_log.status</code>.
     * (RUNNING/SUCCESS/FAILURE)
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.status</code>.
     * (RUNNING/SUCCESS/FAILURE)
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.schedule_execution_log.node_ip</code>.
     */
    public void setNodeIp(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.node_ip</code>.
     */
    public String getNodeIp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.schedule_execution_log.node_name</code>.
     */
    public void setNodeName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.schedule_execution_log.lock_id</code>.
     */
    public void setLockId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.lock_id</code>.
     */
    public String getLockId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.schedule_execution_log.parameters</code>.
     */
    public void setParameters(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.parameters</code>.
     */
    public String getParameters() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.schedule_execution_log.message</code>.
     */
    public void setMessage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.message</code>.
     */
    public String getMessage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.schedule_execution_log.priority</code>.
     */
    public void setPriority(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.schedule_execution_log.priority</code>.
     */
    public String getPriority() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, Instant, Instant, Long, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, Instant, Instant, Long, String, String, String, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.ID;
    }

    @Override
    public Field<String> field2() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.TASK_NAME;
    }

    @Override
    public Field<Instant> field3() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.START_TIME;
    }

    @Override
    public Field<Instant> field4() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.END_TIME;
    }

    @Override
    public Field<Long> field5() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.DURATION_MS;
    }

    @Override
    public Field<String> field6() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.STATUS;
    }

    @Override
    public Field<String> field7() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.NODE_IP;
    }

    @Override
    public Field<String> field8() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.NODE_NAME;
    }

    @Override
    public Field<String> field9() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.LOCK_ID;
    }

    @Override
    public Field<String> field10() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.PARAMETERS;
    }

    @Override
    public Field<String> field11() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.MESSAGE;
    }

    @Override
    public Field<String> field12() {
        return ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG.PRIORITY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTaskName();
    }

    @Override
    public Instant component3() {
        return getStartTime();
    }

    @Override
    public Instant component4() {
        return getEndTime();
    }

    @Override
    public Long component5() {
        return getDurationMs();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public String component7() {
        return getNodeIp();
    }

    @Override
    public String component8() {
        return getNodeName();
    }

    @Override
    public String component9() {
        return getLockId();
    }

    @Override
    public String component10() {
        return getParameters();
    }

    @Override
    public String component11() {
        return getMessage();
    }

    @Override
    public String component12() {
        return getPriority();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTaskName();
    }

    @Override
    public Instant value3() {
        return getStartTime();
    }

    @Override
    public Instant value4() {
        return getEndTime();
    }

    @Override
    public Long value5() {
        return getDurationMs();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public String value7() {
        return getNodeIp();
    }

    @Override
    public String value8() {
        return getNodeName();
    }

    @Override
    public String value9() {
        return getLockId();
    }

    @Override
    public String value10() {
        return getParameters();
    }

    @Override
    public String value11() {
        return getMessage();
    }

    @Override
    public String value12() {
        return getPriority();
    }

    @Override
    public ScheduleExecutionLogRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value2(String value) {
        setTaskName(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value3(Instant value) {
        setStartTime(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value4(Instant value) {
        setEndTime(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value5(Long value) {
        setDurationMs(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value7(String value) {
        setNodeIp(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value8(String value) {
        setNodeName(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value9(String value) {
        setLockId(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value10(String value) {
        setParameters(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value11(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord value12(String value) {
        setPriority(value);
        return this;
    }

    @Override
    public ScheduleExecutionLogRecord values(String value1, String value2, Instant value3, Instant value4, Long value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleExecutionLogRecord
     */
    public ScheduleExecutionLogRecord() {
        super(ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG);
    }

    /**
     * Create a detached, initialised ScheduleExecutionLogRecord
     */
    public ScheduleExecutionLogRecord(String id, String taskName, Instant startTime, Instant endTime, Long durationMs, String status, String nodeIp, String nodeName, String lockId, String parameters, String message, String priority) {
        super(ScheduleExecutionLog.SCHEDULE_EXECUTION_LOG);

        setId(id);
        setTaskName(taskName);
        setStartTime(startTime);
        setEndTime(endTime);
        setDurationMs(durationMs);
        setStatus(status);
        setNodeIp(nodeIp);
        setNodeName(nodeName);
        setLockId(lockId);
        setParameters(parameters);
        setMessage(message);
        setPriority(priority);
        resetChangedOnNotNull();
    }
}
