/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.SupportedTimezone;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupportedTimezoneRecord extends UpdatableRecordImpl<SupportedTimezoneRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supported_timezone.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supported_timezone.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.supported_timezone.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supported_timezone.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.supported_timezone.utc_offset</code>.
     */
    public void setUtcOffset(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supported_timezone.utc_offset</code>.
     */
    public String getUtcOffset() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SupportedTimezone.SUPPORTED_TIMEZONE.ID;
    }

    @Override
    public Field<String> field2() {
        return SupportedTimezone.SUPPORTED_TIMEZONE.DISPLAY_NAME;
    }

    @Override
    public Field<String> field3() {
        return SupportedTimezone.SUPPORTED_TIMEZONE.UTC_OFFSET;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDisplayName();
    }

    @Override
    public String component3() {
        return getUtcOffset();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDisplayName();
    }

    @Override
    public String value3() {
        return getUtcOffset();
    }

    @Override
    public SupportedTimezoneRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SupportedTimezoneRecord value2(String value) {
        setDisplayName(value);
        return this;
    }

    @Override
    public SupportedTimezoneRecord value3(String value) {
        setUtcOffset(value);
        return this;
    }

    @Override
    public SupportedTimezoneRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupportedTimezoneRecord
     */
    public SupportedTimezoneRecord() {
        super(SupportedTimezone.SUPPORTED_TIMEZONE);
    }

    /**
     * Create a detached, initialised SupportedTimezoneRecord
     */
    public SupportedTimezoneRecord(String id, String displayName, String utcOffset) {
        super(SupportedTimezone.SUPPORTED_TIMEZONE);

        setId(id);
        setDisplayName(displayName);
        setUtcOffset(utcOffset);
        resetChangedOnNotNull();
    }
}
