/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.UserProfilePic;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfilePicRecord extends UpdatableRecordImpl<UserProfilePicRecord> implements Record2<String, byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_profile_pic.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_profile_pic.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_profile_pic.profile_pic</code>.
     */
    public void setProfilePic(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_profile_pic.profile_pic</code>.
     */
    public byte[] getProfilePic() {
        return (byte[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, byte[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserProfilePic.USER_PROFILE_PIC.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return UserProfilePic.USER_PROFILE_PIC.PROFILE_PIC;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getProfilePic();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getProfilePic();
    }

    @Override
    public UserProfilePicRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfilePicRecord value2(byte[] value) {
        setProfilePic(value);
        return this;
    }

    @Override
    public UserProfilePicRecord values(String value1, byte[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfilePicRecord
     */
    public UserProfilePicRecord() {
        super(UserProfilePic.USER_PROFILE_PIC);
    }

    /**
     * Create a detached, initialised UserProfilePicRecord
     */
    public UserProfilePicRecord(String id, byte[] profilePic) {
        super(UserProfilePic.USER_PROFILE_PIC);

        setId(id);
        setProfilePic(profilePic);
        resetChangedOnNotNull();
    }
}
