/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.UserNotification;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserNotificationRecord extends UpdatableRecordImpl<UserNotificationRecord> implements Record7<String, String, String, String, Boolean, Instant, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_notification.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_notification.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_notification.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_notification.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_notification.notification_id</code>.
     */
    public void setNotificationId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_notification.notification_id</code>.
     */
    public String getNotificationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_notification.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_notification.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_notification.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_notification.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.user_notification.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_notification.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.user_notification.modified_at</code>.
     */
    public void setModifiedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_notification.modified_at</code>.
     */
    public Instant getModifiedAt() {
        return (Instant) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, Boolean, Instant, Instant> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, Boolean, Instant, Instant> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserNotification.USER_NOTIFICATION.ID;
    }

    @Override
    public Field<String> field2() {
        return UserNotification.USER_NOTIFICATION.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserNotification.USER_NOTIFICATION.NOTIFICATION_ID;
    }

    @Override
    public Field<String> field4() {
        return UserNotification.USER_NOTIFICATION.STATUS;
    }

    @Override
    public Field<Boolean> field5() {
        return UserNotification.USER_NOTIFICATION.ACTIVE;
    }

    @Override
    public Field<Instant> field6() {
        return UserNotification.USER_NOTIFICATION.CREATED_AT;
    }

    @Override
    public Field<Instant> field7() {
        return UserNotification.USER_NOTIFICATION.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getNotificationId();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public Boolean component5() {
        return getActive();
    }

    @Override
    public Instant component6() {
        return getCreatedAt();
    }

    @Override
    public Instant component7() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getNotificationId();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public Boolean value5() {
        return getActive();
    }

    @Override
    public Instant value6() {
        return getCreatedAt();
    }

    @Override
    public Instant value7() {
        return getModifiedAt();
    }

    @Override
    public UserNotificationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserNotificationRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserNotificationRecord value3(String value) {
        setNotificationId(value);
        return this;
    }

    @Override
    public UserNotificationRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserNotificationRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public UserNotificationRecord value6(Instant value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserNotificationRecord value7(Instant value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public UserNotificationRecord values(String value1, String value2, String value3, String value4, Boolean value5, Instant value6, Instant value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserNotificationRecord
     */
    public UserNotificationRecord() {
        super(UserNotification.USER_NOTIFICATION);
    }

    /**
     * Create a detached, initialised UserNotificationRecord
     */
    public UserNotificationRecord(String id, String userId, String notificationId, String status, Boolean active, Instant createdAt, Instant modifiedAt) {
        super(UserNotification.USER_NOTIFICATION);

        setId(id);
        setUserId(userId);
        setNotificationId(notificationId);
        setStatus(status);
        setActive(active);
        setCreatedAt(createdAt);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
