/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.User;

import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.mobile_no</code>.
     */
    public void setMobileNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.mobile_no</code>.
     */
    public String getMobileNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.activation_code</code>.
     */
    public void setActivationCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user.activation_code</code>.
     */
    public String getActivationCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.user.verification_code</code>.
     */
    public void setVerificationCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user.verification_code</code>.
     */
    public String getVerificationCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.user.verification_code_sent_at</code>.
     */
    public void setVerificationCodeSentAt(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user.verification_code_sent_at</code>.
     */
    public Instant getVerificationCodeSentAt() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.user.new_email</code>.
     */
    public void setNewEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user.new_email</code>.
     */
    public String getNewEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.user.reset_code</code>.
     */
    public void setResetCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.user.reset_code</code>.
     */
    public String getResetCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.user.reset_at</code>.
     */
    public void setResetAt(Instant value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.user.reset_at</code>.
     */
    public Instant getResetAt() {
        return (Instant) get(11);
    }

    /**
     * Setter for <code>public.user.remark</code>.
     */
    public void setRemark(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.user.remark</code>.
     */
    public String getRemark() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.user.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.user.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.user.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.user.account_expires_at</code>.
     */
    public void setAccountExpiresAt(Instant value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.user.account_expires_at</code>.
     */
    public Instant getAccountExpiresAt() {
        return (Instant) get(15);
    }

    /**
     * Setter for <code>public.user.password_expires_at</code>.
     */
    public void setPasswordExpiresAt(Instant value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.user.password_expires_at</code>.
     */
    public Instant getPasswordExpiresAt() {
        return (Instant) get(16);
    }

    /**
     * Setter for <code>public.user.last_sign_in_at</code>.
     */
    public void setLastSignInAt(Instant value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.user.last_sign_in_at</code>.
     */
    public Instant getLastSignInAt() {
        return (Instant) get(17);
    }

    /**
     * Setter for <code>public.user.locale</code>.
     */
    public void setLocale(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.user.locale</code>.
     */
    public String getLocale() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.user.time_zone_id</code>.
     */
    public void setTimeZoneId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.user.time_zone_id</code>.
     */
    public String getTimeZoneId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.user.date_time_format_id</code>.
     */
    public void setDateTimeFormatId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.user.date_time_format_id</code>.
     */
    public String getDateTimeFormatId() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.user.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.user.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(21);
    }

    /**
     * Setter for <code>public.user.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.user.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.user.modified_at</code>.
     */
    public void setModifiedAt(Instant value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.user.modified_at</code>.
     */
    public Instant getModifiedAt() {
        return (Instant) get(23);
    }

    /**
     * Setter for <code>public.user.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.user.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String username, String email, String mobileNo, String firstName, String lastName, String passwordHash, String activationCode, String verificationCode, Instant verificationCodeSentAt, String newEmail, String resetCode, Instant resetAt, String remark, Boolean activated, Boolean enabled, Instant accountExpiresAt, Instant passwordExpiresAt, Instant lastSignInAt, String locale, String timeZoneId, String dateTimeFormatId, Instant createdAt, String createdBy, Instant modifiedAt, String modifiedBy) {
        super(User.USER);

        setUsername(username);
        setEmail(email);
        setMobileNo(mobileNo);
        setFirstName(firstName);
        setLastName(lastName);
        setPasswordHash(passwordHash);
        setActivationCode(activationCode);
        setVerificationCode(verificationCode);
        setVerificationCodeSentAt(verificationCodeSentAt);
        setNewEmail(newEmail);
        setResetCode(resetCode);
        setResetAt(resetAt);
        setRemark(remark);
        setActivated(activated);
        setEnabled(enabled);
        setAccountExpiresAt(accountExpiresAt);
        setPasswordExpiresAt(passwordExpiresAt);
        setLastSignInAt(lastSignInAt);
        setLocale(locale);
        setTimeZoneId(timeZoneId);
        setDateTimeFormatId(dateTimeFormatId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        resetChangedOnNotNull();
    }
}
