# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.7.1/reference/html/application-properties.html#application-properties
# ===================================================================
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/passport?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password:
    liquibase:
        change-log: classpath:config/liquibase/master.xml
# ===================================================================
# Application specific properties
# ===================================================================
application:
    server:
        address: http://127.0.0.1:${server.port}