spring:
  datasource:
    url: jdbc:postgresql://aaa:5432/luix-passport
    username: postgres
    password:
  liquibase:
    enabled: true
    drop-first: true # reset database
server:
  forward-headers-strategy: framework # Resolved http CORS block issue
# ===================================================================
# Application specific properties
# ===================================================================
application:
  company:
    force-to-https: true
  allowed-cors:
    mappings:
      "[/logout]": https://passport.luixtech.cn/
      "[/login?logout]": http://passport.luixtech.cn/