version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=derby
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=U2VjdXJlUmFuZG9tTmFjb3NLZXlGb3JKV1RBdXRoZW50aWNhdGlvbjEyMzQ1Njc4OTBhYmNkZWY=
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      - nacos_net
networks:
  nacos_net:
    driver: bridge