# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties
# ===================================================================
app:
    id: passport-client
    name: passport-client
    version: 1.0.0
    package: org.infinity.passport.client
    companyName: Infinity Organization
spring:
    application:
        name: ${app.id}
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: test
    messages:
        basename: i18n/messages
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
    aop:
        proxy-target-class: true
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 9020
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    config: classpath:config/logback-spring.xml
    file:
        path: ${user.home}${file.separator}Log${file.separator}${spring.application.name}${file.separator}${spring.application.name}
    level:
        root: DEBUG
security:
    oauth2:
        client: # used by org.springframework.boot.autoconfigure.security.oauth2.OAuth2ClientProperties
            clientId: internal-client
            clientSecret: 65G-HD9-4PD-j9F-HP5
            accessTokenUri: ${zuul.routes.sso-server.url}/oauth/token
            userAuthorizationUri: ${zuul.routes.sso-server.url}/oauth/authorize
        resource:
            userInfoUri: ${zuul.routes.sso-server-account-open-api.url}/user
zuul:
#    add-proxy-headers: true
    sensitiveHeaders: Cookie,Set-Cookie # Note: sensitiveHeaders: Cookie is very important
#    ignoredPatterns: /**/health/**,/**/mappings/**
#    ignored-services: "*"
    routes:
        sso-server:
            url: http://127.0.0.1:9010
        sso-server-account:
            path: /api/accounts/**
            url: ${zuul.routes.sso-server.url}/api/accounts
        sso-server-account-open-api:
            path: /open-api/accounts/**
            url: ${zuul.routes.sso-server.url}/open-api/accounts
# ===================================================================
# Application specific properties
# ===================================================================
