/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.Oauth2RegisteredClientRecord;

import java.time.Instant;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function19;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row19;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Oauth2RegisteredClient extends TableImpl<Oauth2RegisteredClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.oauth2_registered_client</code>
     */
    public static final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = new Oauth2RegisteredClient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Oauth2RegisteredClientRecord> getRecordType() {
        return Oauth2RegisteredClientRecord.class;
    }

    /**
     * The column <code>public.oauth2_registered_client.id</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.client_id</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>public.oauth2_registered_client.client_id_issued_at</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, Instant> CLIENT_ID_ISSUED_AT = createField(DSL.name("client_id_issued_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "");

    /**
     * The column <code>public.oauth2_registered_client.client_secret</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CLIENT_SECRET = createField(DSL.name("client_secret"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column
     * <code>public.oauth2_registered_client.client_secret_expires_at</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, Instant> CLIENT_SECRET_EXPIRES_AT = createField(DSL.name("client_secret_expires_at"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.oauth2_registered_client.client_name</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CLIENT_NAME = createField(DSL.name("client_name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column
     * <code>public.oauth2_registered_client.client_authentication_methods</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CLIENT_AUTHENTICATION_METHODS = createField(DSL.name("client_authentication_methods"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column
     * <code>public.oauth2_registered_client.authorization_grant_types</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> AUTHORIZATION_GRANT_TYPES = createField(DSL.name("authorization_grant_types"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.redirect_uris</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> REDIRECT_URIS = createField(DSL.name("redirect_uris"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column
     * <code>public.oauth2_registered_client.post_logout_redirect_uris</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> POST_LOGOUT_REDIRECT_URIS = createField(DSL.name("post_logout_redirect_uris"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>public.oauth2_registered_client.scopes</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> SCOPES = createField(DSL.name("scopes"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.client_settings</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CLIENT_SETTINGS = createField(DSL.name("client_settings"), SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.token_settings</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> TOKEN_SETTINGS = createField(DSL.name("token_settings"), SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.photo</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, byte[]> PHOTO = createField(DSL.name("photo"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.oauth2_registered_client.enabled</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.oauth2_registered_client.created_at</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.created_by</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.oauth2_registered_client.updated_at</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.oauth2_registered_client.updated_by</code>.
     */
    public final TableField<Oauth2RegisteredClientRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    private Oauth2RegisteredClient(Name alias, Table<Oauth2RegisteredClientRecord> aliased) {
        this(alias, aliased, null);
    }

    private Oauth2RegisteredClient(Name alias, Table<Oauth2RegisteredClientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.oauth2_registered_client</code> table
     * reference
     */
    public Oauth2RegisteredClient(String alias) {
        this(DSL.name(alias), OAUTH2_REGISTERED_CLIENT);
    }

    /**
     * Create an aliased <code>public.oauth2_registered_client</code> table
     * reference
     */
    public Oauth2RegisteredClient(Name alias) {
        this(alias, OAUTH2_REGISTERED_CLIENT);
    }

    /**
     * Create a <code>public.oauth2_registered_client</code> table reference
     */
    public Oauth2RegisteredClient() {
        this(DSL.name("oauth2_registered_client"), null);
    }

    public <O extends Record> Oauth2RegisteredClient(Table<O> child, ForeignKey<O, Oauth2RegisteredClientRecord> key) {
        super(child, key, OAUTH2_REGISTERED_CLIENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Oauth2RegisteredClientRecord> getPrimaryKey() {
        return Keys.OAUTH2_REGISTERED_CLIENT_PKEY;
    }

    @Override
    public Oauth2RegisteredClient as(String alias) {
        return new Oauth2RegisteredClient(DSL.name(alias), this);
    }

    @Override
    public Oauth2RegisteredClient as(Name alias) {
        return new Oauth2RegisteredClient(alias, this);
    }

    @Override
    public Oauth2RegisteredClient as(Table<?> alias) {
        return new Oauth2RegisteredClient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Oauth2RegisteredClient rename(String name) {
        return new Oauth2RegisteredClient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Oauth2RegisteredClient rename(Name name) {
        return new Oauth2RegisteredClient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Oauth2RegisteredClient rename(Table<?> name) {
        return new Oauth2RegisteredClient(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row19 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row19<String, String, Instant, String, Instant, String, String, String, String, String, String, String, String, byte[], Boolean, Instant, String, Instant, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function19<? super String, ? super String, ? super Instant, ? super String, ? super Instant, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super byte[], ? super Boolean, ? super Instant, ? super String, ? super Instant, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function19<? super String, ? super String, ? super Instant, ? super String, ? super Instant, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super byte[], ? super Boolean, ? super Instant, ? super String, ? super Instant, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
