/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.OrgUserRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrgUser extends TableImpl<OrgUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.org_user</code>
     */
    public static final OrgUser ORG_USER = new OrgUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUserRecord> getRecordType() {
        return OrgUserRecord.class;
    }

    /**
     * The column <code>public.org_user.id</code>.
     */
    public final TableField<OrgUserRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.org_user.org_id</code>.
     */
    public final TableField<OrgUserRecord, String> ORG_ID = createField(DSL.name("org_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.org_user.user_id</code>.
     */
    public final TableField<OrgUserRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private OrgUser(Name alias, Table<OrgUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgUser(Name alias, Table<OrgUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.org_user</code> table reference
     */
    public OrgUser(String alias) {
        this(DSL.name(alias), ORG_USER);
    }

    /**
     * Create an aliased <code>public.org_user</code> table reference
     */
    public OrgUser(Name alias) {
        this(alias, ORG_USER);
    }

    /**
     * Create a <code>public.org_user</code> table reference
     */
    public OrgUser() {
        this(DSL.name("org_user"), null);
    }

    public <O extends Record> OrgUser(Table<O> child, ForeignKey<O, OrgUserRecord> key) {
        super(child, key, ORG_USER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrgUserRecord> getPrimaryKey() {
        return Keys.ORG_USER_PKEY;
    }

    @Override
    public List<ForeignKey<OrgUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORG_USER__FK_ORG_USER_USER_ID);
    }

    private transient User _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.ORG_USER__FK_ORG_USER_USER_ID);

        return _user;
    }

    @Override
    public OrgUser as(String alias) {
        return new OrgUser(DSL.name(alias), this);
    }

    @Override
    public OrgUser as(Name alias) {
        return new OrgUser(alias, this);
    }

    @Override
    public OrgUser as(Table<?> alias) {
        return new OrgUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUser rename(String name) {
        return new OrgUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUser rename(Name name) {
        return new OrgUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUser rename(Table<?> name) {
        return new OrgUser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
