/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.ScheduleExecutionLogRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScheduleExecutionLog extends TableImpl<ScheduleExecutionLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.schedule_execution_log</code>
     */
    public static final ScheduleExecutionLog SCHEDULE_EXECUTION_LOG = new ScheduleExecutionLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduleExecutionLogRecord> getRecordType() {
        return ScheduleExecutionLogRecord.class;
    }

    /**
     * The column <code>public.schedule_execution_log.id</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.schedule_execution_log.task_name</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> TASK_NAME = createField(DSL.name("task_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.schedule_execution_log.start_time</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, Instant> START_TIME = createField(DSL.name("start_time"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.schedule_execution_log.end_time</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, Instant> END_TIME = createField(DSL.name("end_time"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.schedule_execution_log.duration_ms</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, Long> DURATION_MS = createField(DSL.name("duration_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.schedule_execution_log.status</code>.
     * (RUNNING/SUCCESS/FAILED)
     */
    public final TableField<ScheduleExecutionLogRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "(RUNNING/SUCCESS/FAILED)");

    /**
     * The column <code>public.schedule_execution_log.node_ip</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> NODE_IP = createField(DSL.name("node_ip"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>public.schedule_execution_log.node_name</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> NODE_NAME = createField(DSL.name("node_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.schedule_execution_log.scheduler_lock_id</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> SCHEDULER_LOCK_ID = createField(DSL.name("scheduler_lock_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.schedule_execution_log.parameters</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> PARAMETERS = createField(DSL.name("parameters"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.schedule_execution_log.message</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.schedule_execution_log.priority</code>.
     */
    public final TableField<ScheduleExecutionLogRecord, String> PRIORITY = createField(DSL.name("priority"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private ScheduleExecutionLog(Name alias, Table<ScheduleExecutionLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScheduleExecutionLog(Name alias, Table<ScheduleExecutionLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.schedule_execution_log</code> table
     * reference
     */
    public ScheduleExecutionLog(String alias) {
        this(DSL.name(alias), SCHEDULE_EXECUTION_LOG);
    }

    /**
     * Create an aliased <code>public.schedule_execution_log</code> table
     * reference
     */
    public ScheduleExecutionLog(Name alias) {
        this(alias, SCHEDULE_EXECUTION_LOG);
    }

    /**
     * Create a <code>public.schedule_execution_log</code> table reference
     */
    public ScheduleExecutionLog() {
        this(DSL.name("schedule_execution_log"), null);
    }

    public <O extends Record> ScheduleExecutionLog(Table<O> child, ForeignKey<O, ScheduleExecutionLogRecord> key) {
        super(child, key, SCHEDULE_EXECUTION_LOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ScheduleExecutionLogRecord> getPrimaryKey() {
        return Keys.SCHEDULE_EXECUTION_LOG_PKEY;
    }

    @Override
    public List<ForeignKey<ScheduleExecutionLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SCHEDULE_EXECUTION_LOG__FK_SCHEDULE_EXECUTION_LOG_SCHEDULER_LOCK_ID);
    }

    private transient SchedulerLock _schedulerLock;

    /**
     * Get the implicit join path to the <code>public.scheduler_lock</code>
     * table.
     */
    public SchedulerLock schedulerLock() {
        if (_schedulerLock == null)
            _schedulerLock = new SchedulerLock(this, Keys.SCHEDULE_EXECUTION_LOG__FK_SCHEDULE_EXECUTION_LOG_SCHEDULER_LOCK_ID);

        return _schedulerLock;
    }

    @Override
    public ScheduleExecutionLog as(String alias) {
        return new ScheduleExecutionLog(DSL.name(alias), this);
    }

    @Override
    public ScheduleExecutionLog as(Name alias) {
        return new ScheduleExecutionLog(alias, this);
    }

    @Override
    public ScheduleExecutionLog as(Table<?> alias) {
        return new ScheduleExecutionLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScheduleExecutionLog rename(String name) {
        return new ScheduleExecutionLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScheduleExecutionLog rename(Name name) {
        return new ScheduleExecutionLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScheduleExecutionLog rename(Table<?> name) {
        return new ScheduleExecutionLog(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, Instant, Instant, Long, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super String, ? super String, ? super Instant, ? super Instant, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super String, ? super String, ? super Instant, ? super Instant, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
