/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.ShedlockRecord;

import java.time.Instant;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Shedlock extends TableImpl<ShedlockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shedlock</code>
     */
    public static final Shedlock SHEDLOCK = new Shedlock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShedlockRecord> getRecordType() {
        return ShedlockRecord.class;
    }

    /**
     * The column <code>public.shedlock.id</code>.
     */
    public final TableField<ShedlockRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.shedlock.lock_until</code>.
     */
    public final TableField<ShedlockRecord, Instant> LOCK_UNTIL = createField(DSL.name("lock_until"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.shedlock.locked_at</code>.
     */
    public final TableField<ShedlockRecord, Instant> LOCKED_AT = createField(DSL.name("locked_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.shedlock.locked_by</code>.
     */
    public final TableField<ShedlockRecord, String> LOCKED_BY = createField(DSL.name("locked_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Shedlock(Name alias, Table<ShedlockRecord> aliased) {
        this(alias, aliased, null);
    }

    private Shedlock(Name alias, Table<ShedlockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.shedlock</code> table reference
     */
    public Shedlock(String alias) {
        this(DSL.name(alias), SHEDLOCK);
    }

    /**
     * Create an aliased <code>public.shedlock</code> table reference
     */
    public Shedlock(Name alias) {
        this(alias, SHEDLOCK);
    }

    /**
     * Create a <code>public.shedlock</code> table reference
     */
    public Shedlock() {
        this(DSL.name("shedlock"), null);
    }

    public <O extends Record> Shedlock(Table<O> child, ForeignKey<O, ShedlockRecord> key) {
        super(child, key, SHEDLOCK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ShedlockRecord> getPrimaryKey() {
        return Keys.SHEDLOCK_PKEY;
    }

    @Override
    public Shedlock as(String alias) {
        return new Shedlock(DSL.name(alias), this);
    }

    @Override
    public Shedlock as(Name alias) {
        return new Shedlock(alias, this);
    }

    @Override
    public Shedlock as(Table<?> alias) {
        return new Shedlock(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shedlock rename(String name) {
        return new Shedlock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shedlock rename(Name name) {
        return new Shedlock(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shedlock rename(Table<?> name) {
        return new Shedlock(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Instant, Instant, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super Instant, ? super Instant, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super Instant, ? super Instant, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
