/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.SupportedDateTimeFormatRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupportedDateTimeFormat extends TableImpl<SupportedDateTimeFormatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supported_date_time_format</code>
     */
    public static final SupportedDateTimeFormat SUPPORTED_DATE_TIME_FORMAT = new SupportedDateTimeFormat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupportedDateTimeFormatRecord> getRecordType() {
        return SupportedDateTimeFormatRecord.class;
    }

    /**
     * The column <code>public.supported_date_time_format.id</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.supported_date_time_format.display_name</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>public.supported_date_time_format.date_time_format</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> DATE_TIME_FORMAT = createField(DSL.name("date_time_format"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.supported_date_time_format.date_format</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> DATE_FORMAT = createField(DSL.name("date_format"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.supported_date_time_format.time_format</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> TIME_FORMAT = createField(DSL.name("time_format"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.supported_date_time_format.example</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, String> EXAMPLE = createField(DSL.name("example"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.supported_date_time_format.preset</code>.
     */
    public final TableField<SupportedDateTimeFormatRecord, Boolean> PRESET = createField(DSL.name("preset"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private SupportedDateTimeFormat(Name alias, Table<SupportedDateTimeFormatRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupportedDateTimeFormat(Name alias, Table<SupportedDateTimeFormatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supported_date_time_format</code> table
     * reference
     */
    public SupportedDateTimeFormat(String alias) {
        this(DSL.name(alias), SUPPORTED_DATE_TIME_FORMAT);
    }

    /**
     * Create an aliased <code>public.supported_date_time_format</code> table
     * reference
     */
    public SupportedDateTimeFormat(Name alias) {
        this(alias, SUPPORTED_DATE_TIME_FORMAT);
    }

    /**
     * Create a <code>public.supported_date_time_format</code> table reference
     */
    public SupportedDateTimeFormat() {
        this(DSL.name("supported_date_time_format"), null);
    }

    public <O extends Record> SupportedDateTimeFormat(Table<O> child, ForeignKey<O, SupportedDateTimeFormatRecord> key) {
        super(child, key, SUPPORTED_DATE_TIME_FORMAT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SupportedDateTimeFormatRecord> getPrimaryKey() {
        return Keys.SUPPORTED_DATE_TIME_FORMAT_PKEY;
    }

    @Override
    public SupportedDateTimeFormat as(String alias) {
        return new SupportedDateTimeFormat(DSL.name(alias), this);
    }

    @Override
    public SupportedDateTimeFormat as(Name alias) {
        return new SupportedDateTimeFormat(alias, this);
    }

    @Override
    public SupportedDateTimeFormat as(Table<?> alias) {
        return new SupportedDateTimeFormat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportedDateTimeFormat rename(String name) {
        return new SupportedDateTimeFormat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportedDateTimeFormat rename(Name name) {
        return new SupportedDateTimeFormat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportedDateTimeFormat rename(Table<?> name) {
        return new SupportedDateTimeFormat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
