/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.TeamUserRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamUser extends TableImpl<TeamUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team_user</code>
     */
    public static final TeamUser TEAM_USER = new TeamUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamUserRecord> getRecordType() {
        return TeamUserRecord.class;
    }

    /**
     * The column <code>public.team_user.id</code>.
     */
    public final TableField<TeamUserRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.team_user.team_id</code>.
     */
    public final TableField<TeamUserRecord, String> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.team_user.username</code>.
     */
    public final TableField<TeamUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private TeamUser(Name alias, Table<TeamUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TeamUser(Name alias, Table<TeamUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.team_user</code> table reference
     */
    public TeamUser(String alias) {
        this(DSL.name(alias), TEAM_USER);
    }

    /**
     * Create an aliased <code>public.team_user</code> table reference
     */
    public TeamUser(Name alias) {
        this(alias, TEAM_USER);
    }

    /**
     * Create a <code>public.team_user</code> table reference
     */
    public TeamUser() {
        this(DSL.name("team_user"), null);
    }

    public <O extends Record> TeamUser(Table<O> child, ForeignKey<O, TeamUserRecord> key) {
        super(child, key, TEAM_USER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TeamUserRecord> getPrimaryKey() {
        return Keys.TEAM_USER_PKEY;
    }

    @Override
    public List<ForeignKey<TeamUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAM_USER__FK_TEAM_USER_USERNAME);
    }

    private transient User _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.TEAM_USER__FK_TEAM_USER_USERNAME);

        return _user;
    }

    @Override
    public TeamUser as(String alias) {
        return new TeamUser(DSL.name(alias), this);
    }

    @Override
    public TeamUser as(Name alias) {
        return new TeamUser(alias, this);
    }

    @Override
    public TeamUser as(Table<?> alias) {
        return new TeamUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(String name) {
        return new TeamUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(Name name) {
        return new TeamUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(Table<?> name) {
        return new TeamUser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
