/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Indexes;
import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.Public;
import cn.luixtech.passport.server.persistence.tables.records.UserProfilePicRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfilePic extends TableImpl<UserProfilePicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_profile_pic</code>
     */
    public static final UserProfilePic USER_PROFILE_PIC = new UserProfilePic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserProfilePicRecord> getRecordType() {
        return UserProfilePicRecord.class;
    }

    /**
     * The column <code>public.user_profile_pic.id</code>.
     */
    public final TableField<UserProfilePicRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.user_profile_pic.profile_pic</code>.
     */
    public final TableField<UserProfilePicRecord, byte[]> PROFILE_PIC = createField(DSL.name("profile_pic"), SQLDataType.BLOB.nullable(false), this, "");

    private UserProfilePic(Name alias, Table<UserProfilePicRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserProfilePic(Name alias, Table<UserProfilePicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_profile_pic</code> table reference
     */
    public UserProfilePic(String alias) {
        this(DSL.name(alias), USER_PROFILE_PIC);
    }

    /**
     * Create an aliased <code>public.user_profile_pic</code> table reference
     */
    public UserProfilePic(Name alias) {
        this(alias, USER_PROFILE_PIC);
    }

    /**
     * Create a <code>public.user_profile_pic</code> table reference
     */
    public UserProfilePic() {
        this(DSL.name("user_profile_pic"), null);
    }

    public <O extends Record> UserProfilePic(Table<O> child, ForeignKey<O, UserProfilePicRecord> key) {
        super(child, key, USER_PROFILE_PIC);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_PROFILE_PIC_ID);
    }

    @Override
    public UniqueKey<UserProfilePicRecord> getPrimaryKey() {
        return Keys.USER_PROFILE_PIC_PKEY;
    }

    @Override
    public List<ForeignKey<UserProfilePicRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_PROFILE_PIC__FK_USER_PROFILE_PIC_USER_ID);
    }

    private transient User _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.USER_PROFILE_PIC__FK_USER_PROFILE_PIC_USER_ID);

        return _user;
    }

    @Override
    public UserProfilePic as(String alias) {
        return new UserProfilePic(DSL.name(alias), this);
    }

    @Override
    public UserProfilePic as(Name alias) {
        return new UserProfilePic(alias, this);
    }

    @Override
    public UserProfilePic as(Table<?> alias) {
        return new UserProfilePic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilePic rename(String name) {
        return new UserProfilePic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilePic rename(Name name) {
        return new UserProfilePic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilePic rename(Table<?> name) {
        return new UserProfilePic(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super byte[], ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super byte[], ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
