"use strict";
(function () {
    'use strict';
    // Do NOT edit this file
    angular
        .module('smartcloudserviceApp')
        .constant('APP_NAME', 'PassportServer')
        .constant('VERSION', '0.0.1-SNAPSHOT')
        .constant('PAGINATION_CONSTANTS', {
            'itemsPerPage': 10
         })
//        .constant('ENV', 'test')
        .constant('DEBUG_INFO_ENABLED', true);
})();