"use strict";
(function () {
    'use strict';
    // Do NOT edit this file
    angular
        .module('smartcloudserviceApp')
        .constant('APP_NAME', 'passport-server')
        .constant('VERSION', '1.0.0')
        .constant('COMPANY_NAME', 'Infinity Organization')
        .constant('PAGINATION_CONSTANTS', {
            'itemsPerPage': 10
         })
        //        .constant('ENV', 'test')
        .constant('DEBUG_INFO_ENABLED', true);
})();