# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties
# ===================================================================
app:
    id: passport-server
    name: passport-server
    version: 1.0.0
    package: org.infinity.passport
    companyName: Infinity Organization
management: # Management http server configuration, used by ManagementServerProperties
    endpoints:
        web:
            base-path: /management
            exposure: # Refer to https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties.actuator
                include:
                    - configprops
                    - env
                    - health
                    - beans
                    - mappings
                    - httptrace
                    - shutdown
                    - auditevents
                    - scheduledtasks
                    - loggers
                    - prometheus
                    - threaddump
    endpoint:
        health: # used by HealthEndpointProperties, Note: it will show health details if it has the access token by Ajax
            enabled: true
            show-details: WHEN_AUTHORIZED
        httptrace:
            enabled: true
        shutdown:
            enabled: true # explicitly enable
    health:
        mail:
            enabled: true
        mongo:
            enabled: true
    metrics:
        export:
            prometheus: # Prometheus is the default metrics backend
                enabled: true
                step: 60
        enable:
            http: true
            jvm: true
            logback: true
            process: true
            system: true
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
        tags:
            application: ${spring.application.name}
        web:
            server:
                request:
                    autotime:
                        enabled: true
spring:
    application:
        name: ${app.id}
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: test
    main:
        allow-bean-definition-overriding: true
    messages:
        basename: i18n/messages
    task:
        execution:
            thread-name-prefix: global-async-task-
            pool:
                core-size: 5
                max-size: 32
                queue-capacity: 1000
        scheduling:
            thread-name-prefix: global-scheduling-
            pool:
                size: 2
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    servlet:
        multipart: # Management http multipart configuration, used by MultipartProperties
            enabled: true
            max-file-size: 30MB
            max-request-size: 30MB
    session: # used by MongoIndexedSessionRepository
        store-type: MONGODB
        mongodb:
            collection-name: HttpSession
    mail: # specific mail property, used by MailProperties
        host: smtp.exmail.qq.com
        username: test@luixtech.com
        password: LoU-UHR-9dH-8G9-F3G
    banner:
        location: classpath:config/banner-company.txt
    data:
        mongodb:
            auto-index-creation: false
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 9010
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
            timeout: 1D # Session timeout in 1 day, Note: this parameter can control the login expiration
            # and this statement can effect spring session, used by SessionProperties
logging:
    config: classpath:config/logback-spring.xml
    file:
        path: ${user.home}${file.separator}Log${file.separator}${spring.application.name}${file.separator}${spring.application.name}
    level:
        root: DEBUG
mongock:
    enabled: false
    track-ignored: true
    change-logs-scan-package:
        - ${app.package}.config.dbmigrations
    mongo-db:
        read-concern: local
        write-concern:
            journal: false
# ===================================================================
# Application specific properties
# ===================================================================
application:
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        logs: # print metrics info to the logs
            enabled: false
            report-frequency: 60 # in seconds
        graphite: # output metrics info to graphite server
            enabled: false
            host: localhost
            port: 2003
            prefix: ${spring.application.name}
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
    swagger:
        enabled: true
        api:
            title: Passport Server API
            description: Passport Server 接口文档
        open-api:
            title: Passport Server Open API
            description: Passport Server 开放接口文档
        version: ${app.version}
        contact-name: Louis
        contact-email: louis@luixtech.com
        host:
    aop-logging:
        enabled: true
        method-whitelist-mode: true
        method-whitelist:
            - AccountController.getTokenUser
    elapsed-time-logging:
        enabled: true
        slow-execution-threshold: 300 # unit: ms
    cors:
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params"
        allow-credentials: true
        max-age: 1800
    user-event-audit:
        enabled: true
    account:
        default-password: ${spring.application.name}
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        display-on-active-profiles: dev,test,demo